# -*- coding: utf-8 -*-
"""ripe.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1On5-Cvn4QmCTykHsHA7DHzNVXme4ZaJZ
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install ultralytics
import ultralytics
ultralytics.checks()

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="ZnovZ1yo5pYdfsKuZxRt")
project = rf.workspace("a-uie0f").project("pisang-2-ad4vz")
version = project.version(3)
dataset = version.download("yolov11")

!yolo train model=yolo11n.pt data=/content/pisang-2-3/data.yaml epochs=100 imgsz=64

!yolo export model=/content/runs/detect/train/weights/best.pt format=torchscript

#ram tidak cukup kalau kode ini di run
from ultralytics import YOLO
model = YOLO('/content/runs/detect/train/weights/best.pt')
# Tambahkan parameter imgsz untuk memperbesar ukuran input
results = model('/content/What color is a ripe banana Banana ripeness scale.mp4', save=True, show=True)  # atau 1280